print("Enter the following details")
print("============================")
name  = input("Enter  name = ")
age = int(input("Enter age = "))
address=input("Enter Address= ")
print("============================")
print("My deatils are\nI am ",name)
print("I am ",age,"Years old")
print("I reside at ",address)