File = open("text.txt","r")
# content = File.read()
# print(content)
print("+++++++++++++++++++++++++++++++")
content1 = File.readline()
content3 = File.readline()
content2 = File.readlines()
print(content1)
print(content3)
print("+++++++++++++++++++++++++++++++")
print(content2)
File.close()