tup = (1,"kavya",23,"keifer")
print(tup)
print(type(tup))
print(id(tup))
print("Accesing using positive indexing")
print(tup[0])
print(tup[1])
print(tup[2])
print("Accesing using negative indexing")
print(tup[-1])
print(tup[-2])
print(tup[-3])
print("Boolean data type")
print(type(True))